# Homework 1 - GA2711

### Question 2.a

In [ ]:
### Since I have an issue in understanding the requirement of the question,
### two solutions are given for scenarios as follows.
### (1) reverse the order of words in a string with spaces to delimite thoese words; 
### (2) simply reverse characters in a string.

### (1)
def reverse_words(s):
    if not s:
        return s
    return ' '.join(s.split()[::-1])

In [8]:
### Test
r1 = reverse_words('Monster Hunter!')
r2 = reverse_words(None)

print(f'Show outcome above:\n{r1}\n{r2}')

Show outcome above:
Hunter! Monster
None


In [9]:
### (2)
def reverse_words(s):
    if not s:
        return s
    return s[::-1]

### Test
r1 = reverse_words('Monster Hunter!')
r2 = reverse_words(None)

print(f'Show outcome above:\n{r1}\n{r2}')

Show outcome above:
!retnuH retsnoM
None


### Question 2.b

In [1]:
def is_even_and_positive(x):
    return True if x > 0 and x % 2 == 0 else False

In [2]:
### Test
n1 = is_even_and_positive(15)
n2 = is_even_and_positive(-20)
n3 = is_even_and_positive(2)
print(f'Test Cases:\n 15: {n1}\n -20: {n2}\n 2: {n3}')

Test Cases:
 15: False
 -20: False
 2: True


### Question 2.c

In [19]:
def second_largest(lst):
    return sorted(lst)[-2]

In [20]:
### Test
print(f'Test Case:\n [5, 2, -1, 3, 0]: {second_largest([5, 2, -1, 3, 0])}')

Test Case:
 [5, 2, -1, 3, 0]: 3


### Question 2.d

In [5]:
def count_chars(s):
    return {char: s.count(char) for char in set(s)}

In [12]:
### Test
print(f'Test Case:\n MonsterHunter: {count_chars("MonsterHunter")}')

Test Case:
 MonsterHunter: {'M': 1, 'u': 1, 's': 1, 'r': 2, 't': 2, 'n': 2, 'H': 1, 'o': 1, 'e': 2}


### Question 2.e

In [13]:
def squares_of_evens(lst):
    return [num ** 2 for num in lst if num % 2 == 0]

In [14]:
### Test
print(f'Test Case:\n [-2, 0, 4, 5]: {squares_of_evens([-2, 0, 4, 5])}')

Test Case:
 [-2, 0, 4, 5]: [4, 0, 16]


### Question 2.f

In [15]:
class BankAccount():
    def __init__(self):
        self.balance = 0 
        print(f'Account Initiated with Balance: ${self.balance}')

    def deposit(self, amount):
        self.balance += amount
        print(f'Current Balance: ${self.balance}')
    
    def withdraw(self, amount):
        if self.balance >= amount:
            self.balance -= amount
            print(f'Current Balance: ${self.balance}')
        else:
            print(f'Insufficient Balance: ${self.balance}')

In [16]:
### Test
acc = BankAccount()
acc.withdraw(100)
acc.deposit(1000)
acc.withdraw(50)

Account Initiated with Balance: $0
Insufficient Balance: $0
Current Balance: $1000
Current Balance: $950


### Question 3 Numpy

In [1]:
import numpy as np

In [3]:
### (a)
mat = np.arange(1, 101).reshape(10, 10)

### Test
print(mat)
print(mat.shape)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
(10, 10)


In [5]:
### (b)
A = np.arange(1, 26).reshape(5, 5)

### Extract
rowOne = A[0, :]
colLast = A[:, -1]
matCenter = A[1:4, 1:4]

### Test
print(A)
print(f'First Row:\n {rowOne}')
print(f'Last Column:\n {colLast}')
print(f'Central Submatrix:\n {matCenter}')

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First Row:
 [1 2 3 4 5]
Last Column:
 [ 5 10 15 20 25]
Central Submatrix:
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [8]:
### (c)
x = np.array([-1.1, 2.4, 0.3, 0.6, 1.9])
zeroOne = x[(x > 0) & (x < 1)]

### Test
print(zeroOne)

[0.3 0.6]


In [ ]:
### (d)
x = np.random.randn(6)
y = np.random.rand(6)

z = x * x + np.sin(y)

### Test
print(z)

[2.41413952 0.35096956 0.6567559  2.01888165 1.63084874 3.08442468]


In [13]:
### (e)
n, d = 6, 3
X = np.random.randn(n, d)
v = np.random.randn(d)

subtract = X - v

### Test
print(f'X: {X}')
print(f'v: {v}')
print(f'Broadcasting Subtraction:\n {subtract}')

X: [[ 1.03053692  0.43492603  1.18321202]
 [ 1.39090267  1.39262964  1.10916394]
 [ 1.2547202  -0.74398235  2.15260418]
 [-0.09436231  1.01555723 -0.60495303]
 [-0.91313741 -0.73937982  1.41315984]
 [-0.61363571 -0.57724532 -1.19755661]]
v: [ 0.25176277 -0.47865519 -0.3487964 ]
Broadcasting Subtraction:
 [[ 0.77877415  0.91358122  1.53200842]
 [ 1.1391399   1.87128484  1.45796034]
 [ 1.00295743 -0.26532716  2.50140058]
 [-0.34612508  1.49421242 -0.25615663]
 [-1.16490018 -0.26072462  1.76195624]
 [-0.86539848 -0.09859013 -0.84876021]]


In [18]:
### (f)
A = np.random.randn(3, 3)
b = np.random.randn(3)

x = np.linalg.solve(A, b)

### Test
print(f'A:\n{A}')
print(f'b:\n{b}')
print('############################################')
print(f'Solution x:\n{x}')
print('############################################')
print(f'Verify if Ax = b:\n {A @ x}')

A:
[[-1.05171357  1.55804772 -1.17210244]
 [ 1.30696619  0.44077996  0.11271002]
 [-0.17049358 -0.69776334 -0.41775741]]
b:
[ 0.8025643 -0.428988   0.9378722]
############################################
Solution x:
[-0.03424651 -0.52576362 -1.35287798]
############################################
Verify if Ax = b:
 [ 0.8025643 -0.428988   0.9378722]
